field: 5d1f2d5b-12f7-4ceb-9685-f8bd68f017a5 # Basic Form Fields
fieldLayouts:
  67e99958-73c9-4eac-bd1a-fc09ed1b8a88:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d0d30187-1d75-4391-93c0-e9650030a8ee # Label
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 20863dde-fa3e-40bd-86dd-895fd66d1a7d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2ff85f53-2b6e-4657-a50a-20efcacc649a # Handle
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d7070e49-dc06-4e20-9b6a-303441ce8216
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dfa0e2b9-5981-416d-83a5-8264c0435961 # Placeholder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f638020d-bc51-4471-8b67-ea9bbfc7c2ea
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d653c2d4-4597-4bc3-b8f4-0bef90b843e9 # Required
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d66225d6-16a6-4a2a-9c90-3884260de547
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 348f1339-9a22-4e57-8a54-439b63e65d0c
        userCondition: null
fields:
  2ff85f53-2b6e-4657-a50a-20efcacc649a: # Handle
    columnSuffix: pjhbsdoq
    contentColumnType: text
    fieldGroup: null
    handle: fieldHandle
    instructions: null
    name: Handle
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  d0d30187-1d75-4391-93c0-e9650030a8ee: # Label
    columnSuffix: npmcywzp
    contentColumnType: text
    fieldGroup: null
    handle: label
    instructions: null
    name: Label
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  d653c2d4-4597-4bc3-b8f4-0bef90b843e9: # Required
    columnSuffix: kckikjav
    contentColumnType: boolean
    fieldGroup: null
    handle: required
    instructions: 'This field is required?'
    name: Required
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Lightswitch
  dfa0e2b9-5981-416d-83a5-8264c0435961: # Placeholder
    columnSuffix: dbnnitkl
    contentColumnType: text
    fieldGroup: null
    handle: placeholder
    instructions: null
    name: Placeholder
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
handle: singleLine
name: 'Single Line'
sortOrder: 1
