defaultPlacement: end
fieldLayouts:
  33ffecde-4b2e-4645-ad54-3c15b2967fcc:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 593fe1e3-cd73-4c6a-9895-efd6001cd477
            warning: null
            width: 100
        name: Content
        uid: 674ed069-566a-4ed5-9ba5-eb80d42f9366
handle: newsCategories
name: 'News Categories'
siteSettings:
  1a78d395-d81a-4b77-8da7-30a49123bbee: # English
    hasUrls: true
    template: pages/_news-category.twig
    uriFormat: 'news/category/{slug}'
structure:
  maxLevels: null
  uid: a23aa2ea-1f11-4fd2-b2ea-e420d27e959d
