columnSuffix: null
contentColumnType: string
fieldGroup: ef8cc244-dfa8-41b1-945d-cb673ae71824 # Common
handle: contentBuilder
instructions: null
name: 'Content Builder'
searchable: false
settings:
  contentTable: '{{%matrixcontent_contentbuilder}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: none
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
