columnSuffix: vgclrinn
contentColumnType: boolean
fieldGroup: ef8cc244-dfa8-41b1-945d-cb673ae71824 # Common
handle: enableNoticeBar
instructions: null
name: 'Enable Notice Bar'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Lightswitch
