columnSuffix: null
contentColumnType: boolean
fieldGroup: ef8cc244-dfa8-41b1-945d-cb673ae71824 # Common
handle: hideFromNav
instructions: null
name: 'Hide from Nav'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
